image: "rust:latest"

stages:
  - build
  - test
  - lint
  - format

build:
  stage: build
  script: cargo check

test:
  stage: test
  script: cargo test

lint:
  stage: lint
  script:
    - rustup component add clippy --quiet
    - cargo clippy -- -D warnings

format:
  stage: format
  script:
    - rustup component add rustfmt --quiet
    - cargo fmt -- --check
